---
- hosts: 172.31.28.172
  become: yes
  tasks:
  - name: i want to excute linux command directly
    command: hostname -f
    register: myresult

  - name: i want to display result
    debug: 
      msg: "{{myresult}}"
  - name: install git
    apt: 
      name: git 
      state: present
    when: myresult.stderr ==""

  - name: install tree
    apt: 
      name: tree
      state: present
    when: myresult.stderr !==""
 