---
- name: create a new tomcat group
  group:
    name: tomcat
    state: present

- name: create new tomcat user
  user:
    name: tomcat
    shell: /bin/false
    home: /opt/tomcat
    group: tomcat
    state: present    
