---
# tasks file for mytom8ubuntu16
- include_tasks: installjava.yml
- include_tasks: createtomcatuser.yml
- include_tasks: installtomcat.yml
- include_tasks: updatepermissions.yml
- include_tasks: createservicefile.yml
- include_tasks: Strtomcat.yml
- include_tasks: tomwebmanagment.yml
